name: CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1'] # , '1.6']  # LTS is failing because HomotopyContinuation is a dependency of the tests it doesn't support the LTS
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x64]
        include:
          # Also test against 32-bit Linux
          - version: '1'
            os: ubuntu-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: dev
        shell: julia --project=@. {0}
        run: |
          using Pkg
          Pkg.add([
              PackageSpec(name="StarAlgebras", rev="mk/non_monomial_basis"),
              PackageSpec(name="MultivariateBases", rev="master"),
              PackageSpec(name="MultivariateMoments", rev="master"),
          ])
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
